#!/bin/bash

docker-compose down -v
docker-compose up -d ms_postgres ms_redis

sleep 5

docker cp dump.sql ms_postgres:/dump.sql
docker exec -i ms_postgres psql -U minsweep -d minsweep -a -f /dump.sql
